### PR TITLE
Add simple state example

### PR DESCRIPTION
**Pull request by joshtriplett**
I found this example useful in understanding how a tide-based server can
handle and maintain state.

### CODE REVIEW

**Comment by joshtriplett** [comment]
Re-pushed with formatting fixed.

**Comment by jbr** [comment]
Thanks! I think we'd probably want to encourage people to put the Arc inside of their State (`struct State { value: Arc<AtomicU32> }` and `Server<State>` instead of `struct State { value: AtomicU32 }` and `Server<Arc<State>>`), since often State will contain types that are already Clone, like database connection pools. Happy to be convinced that this is a better exemplar, though

**Comment by joshtriplett** [comment]
@jbr Perfectly happy to do it that way instead.

**Comment by jbr** [comment]
Thanks!

**Pull request merged**
