### PR TITLE
Don't print anything by default

### PR DESCRIPTION
**Pull request by acasajus**
println! should be avoided so users can decide what to print :)

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@acasajus I don't disagree with removing the println here, though I do think we may want to replace it with a `log::info` statement instead.

**Comment by acasajus** [comment]
If you're already working on a branch that includes this I'll gladly remove my PR. I'm really eager to try tide in my project in stable when 1.39 lands tomorrow. How long do you reckon it will take to stabilise tide?

**Comment by yoshuawuyts** [comment]
@acasajus I'm glad you're excited! If we don't hit any snags I think we should have a new release within a week? Very excited for this too!

**Comment by dzrtc** [comment]
@yoshuawuyts @acasajus Any updates on this?

**Pull request closed without merging**
