### PR TITLE
add more example application

### PR DESCRIPTION
**Pull request by azzamsa**
## Motivation and Context

To make easy for tide users adopt the framework, by using examples

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the [CONTRIBUTING](https://github.com/rustasync/tide/blob/master/.github/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jbr** [comment]
Thanks for adding this! Is it worth mentioning that this is built on tide from quite a while ago and may not represent current best practices or apis?

**Comment by azzamsa** [comment]
> represent current best practices or apis?

if that the requirements of tide project to be posted in "example" section.  Then I have no authoritative answer, since I'm not the author.


@colinbankier is.

**Comment by jbr** [comment]
Fair point. Maybe it's worth keeping a tide version number next to each of these

**Comment by azzamsa** [comment]
Oh, I see your point. Since tide doesn't reach `1.0` yet. So the API will likely change.

Okay, let's add the version number next to the project examples.

**Comment by Fishrock123** [comment]
I don't think we should include out-of-date examples?

**Comment by azzamsa** [comment]
related: https://github.com/http-rs/tide/pull/684

**Comment by jbr** [comment]
I think @Fishrock123's point is worth discussing. What is the purpose of this list, and does adding an outdated example help us meet that goal?

My answer to the former is "to help people structure their tide applications," and I don't see how outdated examples help us meet that goal.  In a mature project I can imagine someone saying "we have to use the old version for various reasons, so having old examples are useful," but I can't think of any reason to build a new tide application with anything older than the most recent release.

@azzamsa What do you think? Who does this help?

**Comment by azzamsa** [comment]
Agree with that. those old version should be in the community maintained list.

**Comment by jbr** [comment]
@azzamsa Why? What's the motivation behind including it in any list, if it doesn't help people use tide

**Comment by azzamsa** [comment]
I learn approach, capabilities, best practices, API from popular *-boilerplates. (* = flask, and other web frameworks).

I want to know how people structure tide in a big project (real-world app), see what it capable of, etc.

It's okay if it's not relevant here.

**Comment by jbr** [comment]
I think it _is_ relevant here, it's just that tide is rapidly changing, and the structure of applications changes as a result of those changes.  In particular, the 0.6 example uses a totally different approach to error handling than current tide apps would use, and that has somewhat far-reaching effects on the structure of an application. I worry that if someone were new to tide, they'd look at this example and not notice that tide's error handling story has improved since 0.6

**Comment by jbr** [comment]
We very much _need_ more examples with different approaches, and I think it would be valuable to the community to bring the realworld.io example up to date so that it can be featured in this list

**Comment by azzamsa** [comment]
Yes, I see your point since the beginning. Tide doesn't reach 1.0 yet. So the API will likely to change fast. We don't want to put any *old* project representing old tide API. We don't want to make people assume that bad old API is the current tide API and make people upset.

**Comment by azzamsa** [comment]
> and I think it would be valuable to the community to bring the realworld.io example up to date so that it can be featured in this list

sure. It will auto-magically happened when tide had a bigger community, some days later, I hope.

**Comment by colinbankier** [comment]
Thanks for considering the example. We would of course like to keep it up to date - I've opened https://github.com/colinbankier/realworld-tide/issues/29.
Also in terms of tide best practices etc, always happy to have issues or PRs opened to help that repo serve as a good example of building a non-trivial tide app.

**Pull request closed without merging**
